NPM = npm
COMMAND = run dev

run:
	$(NPM) $(COMMAND)

install:
	$(NPM) install

# Ajuda para listar os comandos disponíveis
help:
	@echo "Comandos disponíveis:"
	@echo "  make run     - Executa o comando npm run dev"
	@echo "  make install - Instala as dependências do projeto"