# Variáveis para facilitar a manutenção
NPM = npm
COMMAND = start

run:
	$(NPM) $(COMMAND)

install:
	$(NPM) install

help:
	@echo "Comandos disponíveis:"
	@echo "  make run     - Executa o comando npm run dev"
	@echo "  make install - Instala as dependências do projeto"